{
 "title": "MyApp",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS (by endpoint)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myapp_app_request_count[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "RPS  (nginx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "httpCode: {{status}}"
    }
   ]
  },
  {
   "title": "RPS по разным урлам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(myapp_app_request_count[1m])",
     "legendFormat": "RPS: {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency NGINX (квантиль 0.5)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Latency NGINX (квантиль 0.95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Latency NGINX (квантиль 0.99)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Latency by endpoint (квантиль 0.5)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(myapp_app_request_latency_msec_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Latency by endpoint (квантиль 0.95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(myapp_app_request_latency_msec_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Latency by endpoint (квантиль 0.99)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(myapp_app_request_latency_msec_bucket[1m])))"
    }
   ]
  },
  {
   "title": "CPU usage (LA) by pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{container=~\"mysuperapp-myapp-.*\"}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage by pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container)(rate(container_memory_usage_bytes{container=~\"mysuperapp-myapp-.*\"}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "MYSQL количество запросов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])",
     "legendFormat": "запросы"
    }
   ]
  }
 ]
}